# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BitCamp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'StitchCore', '~> 3.0.2'
    # optional: for accessing a mongodb client
    pod 'MongoDBService', '~> 3.0.2'
    # optional: for using mongodb's ExtendedJson
    pod 'ExtendedJson', '~> 2.0.4'
	pod 'Alamofire'
	pod 'AlamofireObjectMapper'
  # Pods for BitCamp

end
